Add Certification Page
target/consensource-ui pull request #56
Opened 2020-09-21 21:05 UTC by trevormcdonald

## Proposed change/fix

- Same general layour as FactoryProfile page
- Displays standard name and factory name at top
- Includes two info sections for cert and cert body info, separate elements
- Add fetchCertificateById to api service
- Add /certifications/:certificationId route

## Types of changes

What types of changes does this pull request introduce to ConsenSource? _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (could be a small readme update, documentation contribution, etc.)

## How to run/test

1. Clone down the [consensource-compose](https://github.com/target/consensource-compose) repo:
```bash
 git clone --recurse-submodules https://github.com/target/consensource-compose.git
```
2. Make sure each submodule is up-to-date with the latest code changes
```sh
 git submodule update --remote $api
```
3. `cd api` and checkout this branch for api submodule
4. Build a local image for this image
```sh
 ./docker-helper.sh --build api
```
5. Build local images for other submodules as well if needed (`./docker-helper.sh --build local`)
6. Run `docker-compose -f docker-compose.run-local.yaml up`
7. Exec into the CLI container
8. Create an agent
```bash
 csrc agent create cliagent --url http://api:9009
```
9. Create an ingestion organization
```bash
 csrc organization create assertororg 4 assertercontactname 7632918628 ENG --city minneapolis --country usa --street_address '821 thor street' --url http://api:9009
```
10. Create a factory assertion
```
 csrc assertion factory create {org_id_here} testfactoryassertion1 yuki 6123982765 JPN --city osaka --country japan --street_address 'fukuoka south st' --state_province kanto --postal_code 55414 --url http://api:9009
```
11. Create a standard assertion
```
csrc assertion standard create {org_id_here} FSC-C 1.0 yeah link 1 --url http://api:9009
```
12. Create a certificate assertion
```
csrc assertion certificate create {assertor_id_here} {factory_id_here} 2 3 {standard_id_here} --url http://api:9009
```
13. View the `Certification` page at `http://localhost:3000/certifications/{cert_id_here}`

2020-09-21 21:38 UTC, Patrick-Erichsen requested changes
Looks awesome 👍 

<img width="1438" alt="Screen Shot 2020-09-21 at 4 31 42 PM" src="https://user-images.githubusercontent.com/20157849/93823768-fc988700-fc27-11ea-8e0d-3f8894880dd3.png">

I was going to make a comment about wanting to add some logic to navigate to this new page through the UI instead of needing to change the URL manually, but to be honest I think this is probably a smaller/more concise PR. We can follow up with some of that logic in a later PR.

BTW - if you haven't tried, a nice way to check out what the loading state for things looks like is to throttle your internet speed in dev tools (`Network` tab, then throttling dropdown in the top nav). Not that anything in particular, looks off but just thought I'd mention it since I recently started doing that when using any loading animations.

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/CertBodyInfo.tsx
> +interface Certificate {
I think renaming this to `CertBodyInfoProps` would be a little more explicit.

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/CertificateInfo.tsx
> +interface Certificate {
I think renaming this to `CertificateInfoProps` would be a little more explicit.

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/Certification.tsx
> +export interface Certification {
I think renaming this to `Certification Props` would be a little more explicit.

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/Certification.tsx
> +  // Including the `expand` param includes certificates with factories
I believe this comment can be removed since we aren't including the expand param.

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/Certification.tsx
> +          <Typography color="error">Failed to load certification</Typography>
I think I added this after you started this work, but I made a `<WarningIconError />` component that I've been trying to use as a generic placeholder for error scenarios on `<LoadingWithMinDisplay />`.

https://github.com/target/consensource-ui/blob/react-refactor/src/view/components/WarningIconError.tsx

This could become just
```jsx
<WarningIconError >
  Failed to load certification
</WarningIconError>
```
(although you may need to adjust the `typeVariant`/`iconFontSize` props)

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/CertificateInfo.tsx
> +        val={new Date(valid_from).toLocaleDateString()}
What are your thoughts on making a `services/utils.ts` file to throw this logic into?

I'm starting to run into a few scenarios on my own where I am duplicating some logic that is very general, similar to how we are parsing dates here. Feels like it is probably wise to make that utils file sooner rather than later.

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/CertBodyInfo.tsx
> +          <Typography color="error">Failed to load factory details</Typography>
Same comment as https://github.com/target/consensource-ui/pull/56/files#diff-a20d1335bc814b47bdf0d56dad9df22bR47

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/CertBodyInfo.tsx
> +      loadingIndicator={<SpinnerWithLabel label="Loading factory info..." />}
```suggestion
      loadingIndicator={<CircularProgress />}
```

I don't have this codified anywhere, but I have been trying to use the `<SpinnerWithLabel />` component mostly for full-page loading, or more generally for a top-level component. 

In this scenario where we are just loading a single component in a larger top-level component, I think it makes more sense to just throw a regular `<CircularProgress />` component into the `loadingIndicator` since the additional context provided by the label isn't really needed IMO.

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/CertBodyInfo.tsx
> +import { InfoItem } from 'view/components/InfoItem';
I believe this can just be imported along with the other components in line 4?

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/CertificateInfo.tsx
> +import { InfoItem } from 'view/components/InfoItem';
```suggestion
import { InfoItem } from 'view/components';
```

2020-09-21 21:38 UTC, Patrick-Erichsen commented on src/view/pages/Certification/CertificateInfo.tsx
> +import { InfoItem } from 'view/components/InfoItem';
I just noticed a few other places in the codebase where we are doing an `import { InfoItem } from 'view/components/InfoItem'` as well. I will clean that up in a future PR.

2020-09-22 13:19 UTC, trevormcdonald commented on src/view/pages/Certification/CertificateInfo.tsx
> +        val={new Date(valid_from).toLocaleDateString()}
Yeah if it pops up in more places.

2020-09-22 14:44 UTC, Patrick-Erichsen approved these changes

2020-09-22 14:44 UTC, Patrick-Erichsen commented on src/view/pages/Certification/CertBodyInfo.tsx
> +          Failed to load certification body Info
```suggestion
          Failed to load certifying body info
```

2020-09-22 14:44 UTC, Patrick-Erichsen commented on src/view/pages/Certification/Certification.tsx
> +      loadingIndicator={<CircularProgress />}
So I think this is a case to actually keep the `<SpinnerWithLabel label="Loading certification..." />`. Take a peek at some of the [MUI usage docs](https://material.io/components/progress-indicators#linear-progress-indicators), particularly the `Placement` section. Those two mp4s are basically what I'm trying to replicate.

2020-09-22 15:23 UTC, merged