Tmcdonald too modal
target/consensource-ui pull request #80
Opened 2020-11-09 21:12 UTC by trevormcdonald

## Proposed change/fix

Describe your change/fix and link to any relevant issues.

## Types of changes

What types of changes does this pull request introduce?

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Visual change (includes a change visible to an end user)
-   [ ] Other (could be a small readme update, documentation contribution, etc.)

## Screenshots (visual updates only)

Include a screenshot of any visual changes.

## How to run/test

Please include instructions on how to run/test your contribution if necessary.

2020-11-18 17:58 UTC, Patrick-Erichsen requested changes

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/modals/TransferFactory.tsx
> +          CLOSE
In this case where we have the big `Claim factory` button at the bottom of the dialog, I think we should avoid having another `Close` button beneath. 

<img width="603" alt="Screen Shot 2020-11-18 at 10 58 58 AM" src="https://user-images.githubusercontent.com/20157849/99562035-3fa77a00-298d-11eb-9e7d-66dab7f8622b.png">

This isn't reflected in the prototype (will update that), but I think it would be preferable to have an `X` in the top right of the dialog to close out, instead of a button in the bottom right.

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/modals/TransferFactory.tsx
> +    <Dialog
Few thoughts here:

- Setting `scroll='body'` will remove the sidebar scroll that I don't think we want
- Setting the following props will give the dialog a bit more width to look less cramped, but not an excessive amount on larger screens ([docs link](https://material-ui.com/components/dialogs/#optional-sizes))

```ts
<Dialog
  fullWidth
  maxWidth="md"
  ...
>
```

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/modals/TransferFactory.tsx
> +        <DialogContentText>
I included the batch status link stuff over in the `Advanced` dropdown mostly as a developer utility, so I don't think we need it here.

The broader reason for having that logic at all is that I would eventually like to develop a feature that shows the status of various batches in a more persistent snackbar type element. E.g.

<img width="523" alt="Screen Shot 2020-11-18 at 11 16 45 AM" src="https://user-images.githubusercontent.com/20157849/99564095-9f9f2000-298f-11eb-9d14-934192dd5a68.png">

Additionally, I anticipate other scenarios where we want to take some action based on whether or not a batch was committed. For now, it's just a develop utility though.

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/CreateContact.tsx
> +  existing_contact?: IContactStrict;
Also -  would it be possible to generalize this logic? E.g. any form can take in an existing object to repopulate? We could do this in `forms/utils` and just have forms that want to enable that functionality extend from it.

I think we could then just use a generic `data` prop to pass objects instead of `existing_xyz`.

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/Organization.tsx
> +        <form>
I am not sure if we need these additional `<form />` tags? I believe as long as they are enclosed in the parent `<form />` there isn't an accessibility issue.

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/Organization.tsx
> +        <form>
Check out this [stackoverflow link](https://stackoverflow.com/questions/4519485/can-i-nest-form-tags-in-other-form-tags)

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/CreateContact.tsx
> +              if (existing_contact) onSubmit(createOrgContact(contact));
What about something like this for all of the places we are using this logic?

```ts
 const submit = (event?: React.FormEvent) => {
    if (event) {
      event.preventDefault();
    }

    onSubmit(createOrgContact(contact));
  };

  const onChange = (
    event: Parameters<NonNullable<TextFieldProps['onChange']>>[0],
    key: keyof IContactStrict,
  ) => {
    setContact({ ...contact, [key]: event.target.value });

    if (existing_contact) {
      submit()
    }
  };
```

and then 

```ts
<TextField onChange={(e) => onChange(e, 'name')} />
```

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/CreateContact.tsx
> +      <Grid item>
So, the only "real" place we are using the create contact & create factory address forms is in the transfer factory dialog, which doesn't require a submit button.

I wouldn't be opposed with just getting rid of the submit button logic in both of these forms. This would simplify the logic in this component a lot imo, and there is no hard requirement for us to keep the submit.

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/CreateContact.tsx
> +      <Grid item>
This sort of negates my big code snippet above regarding `onChange`, but I will leave it in place in case we don't decide to scrap the submit logic.

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/Organization.tsx
> +    if (existing_org.assertion_id) {
So, is it necessarily the case that we always want to transfer the assertion on an update? This is business logic I am not sure of.

Either way, I feel like it would be nice if we could signal this a little more clearly - imo it is a little implicit when we are just relying on a field to be present on the `existing_org` object.

What about including a `transferAssertion` boolean prop on the form? Then,

```ts
if (transferAssertion && hasOwnPropertySafe(existing_org, 'assertion_id') { ... }
```

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/Organization.tsx
> +    if (existing_org.assertion_id) {
Checkout [this eslint rule](https://eslint.org/docs/rules/no-prototype-builtins) as to why we need that `hasOwnPropertySafe` from our `utils/index.ts` file.

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/Organization.tsx
> +            disabled={!signer || (!org.contacts && !org.address)}
I believe `signer` is always a truthy value.

As for the other two, I think you can use `hasEmptyFields` from `'view/forms/utils'`

2020-11-18 17:58 UTC, Patrick-Erichsen commented on src/view/forms/organization/Organization.tsx
> +interface IUpdateOrganizationActionStrict extends IUpdateOrganizationAction {
This is a personal preference, but I like to have all of the interfaces at the top of the file. Also, I have just been `export`ing all interfaces, since I don't really see a downside to it.

2020-11-18 18:14 UTC, Patrick-Erichsen commented on src/view/pages/FactoryProfile/FactoryProfile.tsx
> +          <Grid container item>
Few other thoughts 

- Using the `VerifiedUserOutlined` icon in this component would help reinforce that the icon implies "owned" data throughout the platform
- I think it would be a bit cleaner to wrap the FAB and the transfer dialog in a `ClaimFactoryFab.tsx` component in `src/view/pages/FactoryProfile/FactoryProfile.tsx`

2020-11-18 22:07 UTC, trevormcdonald commented on src/view/forms/organization/CreateContact.tsx
> +  existing_contact?: IContactStrict;
Yes it would be possible but would probably require generics. I would save that work for if/when we make a more general action form.

2020-11-18 22:57 UTC, trevormcdonald commented on src/view/forms/organization/Organization.tsx
> +        <form>
In this case there is no parent form, no nesting occurs.

2020-11-19 14:03 UTC, trevormcdonald commented on src/view/forms/organization/CreateContact.tsx
> +      <Grid item>
I think I would be against getting rid of any existing functionality at this time.

2020-11-19 14:12 UTC, trevormcdonald commented on src/view/forms/organization/Organization.tsx
> +    if (existing_org.assertion_id) {
So whether an org can be transferred or not depends on whether it is an assertion. By introducing a boolean value prop separate from that we would also introduce the possibility of that boolean being out of sync with the data which IMO is less clear than this.

2020-11-19 14:25 UTC, trevormcdonald commented on src/view/forms/organization/Organization.tsx
> +            disabled={!signer || (!org.contacts && !org.address)}
I got rid of the check on `signer`. Address may or may not be required depending on the org type. Changing that check would make this form only work for factories.

2020-11-19 18:43 UTC, adeebahmed approved these changes

2020-11-19 18:52 UTC, Patrick-Erichsen commented on src/view/forms/organization/CreateContact.tsx
> +    event: Parameters<NonNullable<TextFieldProps['onChange']>>[0],
Probably should have thought of this in my original comment, but I feel like this type would be a good candidate for `forms/utils.ts`. Feels generalizable enough to through in there as `onChangeEvent` to avoid copypaste.

2020-11-19 18:56 UTC, Patrick-Erichsen commented on src/view/forms/organization/Organization.tsx
> +      existingOrg.assertion_id &&
Another oversight on my part - I think we can just use the [`isDataClaimed()`](https://github.com/target/consensource-ui/blob/main/src/utils/index.ts#L22) utils method here.

2020-11-19 19:09 UTC, Patrick-Erichsen commented on src/view/pages/FactoryProfile/ClaimFactoryFab.tsx
> +      {!factory.assertion_id || (
I would opt to put this boolean check on the FactoryProfilePage, e.g.

```tsx
{!isDataClaimed && <ClaimFactoryFab factory={factory} /> }
```

I think that is a little more obvious to someone trying to understand the structure of the factory profile that the FAB won't ever display if the factory is claimed.

2020-11-19 19:11 UTC, Patrick-Erichsen commented on src/view/pages/FactoryProfile/ClaimFactoryFab.tsx
> +          style={{
In general I've been trying to avoid in-line styles and use `createStyles()` / `makeStyles()`. 

We can't access any theme related things using the `style` prop, which doesn't matter in this case. But then we end up having two places to find CSS (i.e. via `className` or inline `styles`).

2020-11-19 19:14 UTC, Patrick-Erichsen commented on src/view/pages/FactoryProfile/ClaimFactoryFab.tsx
> +          <VerifiedUserOutlined />
The padding between the icon and the text is a little tight here. Check out the `extendedIcon ` style from [this example](https://material-ui.com/components/floating-action-button/#floating-action-button-2).

That example uses `theme.spacing(1)`, which would be another good reason to not use the `styles` prop above.

2020-11-19 19:19 UTC, Patrick-Erichsen commented on src/view/pages/FactoryProfile/ClaimFactoryFab.tsx
> +import React from 'react';
So, on smaller screens, the FAB can overlap and block content.

<img width="1021" alt="Screen Shot 2020-11-19 at 1 17 20 PM" src="https://user-images.githubusercontent.com/20157849/99713156-96828180-2a69-11eb-8614-96462fb6d4d3.png">

I'm on a laptop, and I need to shrink my browser width by close to 50% to run into that issue. So I don't think it will be a problem until we need to worry about mobile/tablet users, which is not at all on our radar. Just thought I would call it out though.

@BuoyLynn @MattP007

2020-11-19 19:21 UTC, Patrick-Erichsen commented on src/view/pages/FactoryProfile/ClaimFactoryFab.tsx
> +          color="primary"
```suggestion
          color="secondary"
```

2020-11-19 19:37 UTC, Patrick-Erichsen commented on src/view/modals/TransferFactory.tsx
> +          <h2>Confirm Factory Information</h2>
In general, we should use the typography component over vanilla HTML. To be honest, I don't have a great answer as to why that is the case, but I think it more or less boils down to the benefits of doing CSS in JS vs vanilla CSS.

E.g. if we want to change the style of all h2 elements, if we were using vanilla `<h2 />` tags, we could just set a global h2 style in CSS. Or, we could update our MUI theme object, and then all Typography components with `variant="h2"` would update. 

Here's a [link](https://medium.com/@_imGufran/why-use-css-in-js-benefits-and-drawbacks-df40ab4ebef9) if you want to dig into it more.

```suggestion
          <Typography variant="h2">Confirm Factory Information</Typography>
```

2020-11-19 19:38 UTC, Patrick-Erichsen commented on src/view/modals/TransferFactory.tsx
> +  existingOrg: FactoryResData;
Thoughts? 

```suggestion
  existingFactory: FactoryResData;
```

2020-11-19 19:43 UTC, Patrick-Erichsen commented on src/view/modals/TransferFactory.tsx
> +import CloseIcon from '@material-ui/icons/Close';
In general, I have been using named imports/destructuring.

```suggestion
import { Close } from '@material-ui/icons';
```

[More info](https://material-ui.com/components/icons/#usage) on pros/cons of each approach if you're curious.

2020-11-19 20:32 UTC, Patrick-Erichsen commented on src/view/forms/organization/CreateContact.tsx
> +      <Grid item>
Agreed! 👍

2020-11-19 21:08 UTC, Patrick-Erichsen commented on src/view/forms/organization/Organization.tsx
> +  contacts: NonNullable<IContactStrict[]>;
I believe both of these should be like this:

```suggestion
  contacts: NonNullable<IUpdateOrganizationAction['contacts]>;
```

2020-11-19 21:17 UTC, Patrick-Erichsen commented on src/view/forms/organization/Organization.tsx
> +    contacts: existingOrg.contacts as IContactStrict[],
I believe this can just be
```suggestion
    contacts: existingOrg.contacts,
```

I didn't get any TS errors.

2020-11-19 21:18 UTC, Patrick-Erichsen commented on src/view/pages/FactoryProfile/ClaimFactoryFab.tsx
> +    closeButton: {
I would just call this `fab` or something.

2020-11-19 21:19 UTC, Patrick-Erichsen commented on src/view/pages/FactoryProfile/ClaimFactoryFab.tsx
> +export const ClaimFactoryFab = withStyles(styles)(
I don't believe you need the `withStyles` ?

2020-11-19 21:36 UTC, trevormcdonald commented on src/view/forms/organization/Organization.tsx
> +  contacts: NonNullable<IContactStrict[]>;
So those are different types I believe, one is strict and the other is not.

2020-11-19 22:03 UTC, trevormcdonald commented on src/view/forms/organization/Organization.tsx
> +    contacts: existingOrg.contacts as IContactStrict[],
I did get TS errors

2020-11-23 22:30 UTC, merged