Mm create themedlink
target/consensource-ui pull request #86
Opened 2020-11-13 19:30 UTC by merli027

## Proposed change/fix

- ```<ThemedLink/>```  component created with tests
-  Update components to use this new component, with snapshot updates
 -```<GrantedToSubtitle/>```
 -```<FactoryNameCell/>```
 -```<CertificateCell />```
-  Test instance updated

## Types of changes

What types of changes does this pull request introduce?

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Visual change (includes a change visible to an end user)
-   [X ] Other (could be a small readme update, documentation contribution, etc.)

## Screenshots (visual updates only)

NA

## How to run/test

1. ```yarn run``` to check it's working
2. ```yarn run test``` to run tests

2020-11-14 01:28 UTC, Patrick-Erichsen requested changes

2020-11-14 01:28 UTC, Patrick-Erichsen commented on src/view/components/Links/UnstyledLink.tsx
> +import { Link as RouterLink, LinkProps } from 'react-router-dom';
Assuming we go with the logic to consolidate to a single `<Link />` component, we can just delete this entire file.

2020-11-14 01:28 UTC, Patrick-Erichsen commented on src/view/tables/factory/components/CertificatesCell.tsx
> +import { ThemedLink, useStyles } from '../../../components/Links/ThemedLink';
```suggestion
import { ThemedLink } from 'view/components';
```

2020-11-16 14:15 UTC, merli027 commented on src/view/components/Links/ThemedLink.tsx
> +      to={{ pathname: to, state: { ...otherProps } }}
Hi, I tired that and it didn't work. I got a no overload matches this cell. Do you know a fix for this?

2020-11-23 20:43 UTC, merged