Fixed the margin spacing on the validToTest to align with the claimed…
target/consensource-ui pull request #88
Opened 2020-11-17 14:12 UTC by merli027

## Proposed change/fix

Fixed the spacing on the Valid To icon on the certification card.

What types of changes does this pull request introduce?

-   [ X] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Visual change (includes a change visible to an end user)
-   [ ] Other (could be a small readme update, documentation contribution, etc.)

## Screenshots (visual updates only)

<img width="344" alt="Screen Shot 2020-11-17 at 8 09 12 AM" src="https://user-images.githubusercontent.com/60482944/99400210-4f9b5d00-28ac-11eb-9734-00c82801e792.png">

## How to run/test

1. Create a cert using these instructions: https://github.com/target/consensource-ui/pull/56
2. ```Yarn start``` to visually view the change

2020-11-17 15:03 UTC, Patrick-Erichsen requested changes
Checkout how the spacing gets wonky on a 832 x 692 viewport.

<img width="301" alt="Screen Shot 2020-11-17 at 9 01 17 AM" src="https://user-images.githubusercontent.com/20157849/99406440-7e690180-28b3-11eb-9231-84da2e7c5d47.png">

You'll notice that in general, the second row keeps a consistent spacing. We're running into this issue because that one is just an icon, but the `validToText` row is actually a button, which includes some additional padding to enable the hover effect on buttons.

2020-11-24 18:38 UTC, Patrick-Erichsen requested changes

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/MoreInfoLinkButton.tsx
> +import React from 'react';
This whole file can now be deleted I believe.

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +describe('<Certificates />', () => {
```suggestion
describe('<CertificationCard />', () => {
```

This one is a little weird because the file is just named `Certification.tsx`. However, I've been trying to use the actual component name in the describe, so it should be `<CertificationCard />`

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +  });
Having a newline after each `it()` makes things a bit more readable imo.

```suggestion
  });
  
```

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +    userEvent.click(screen.getByText('More Info'));
I don't think this line is really testing anything. We could have a more involved test that clicks on this button and confirms that a new page is rendered, but I don't really feel like that is necessary. Just confirming that the element contains a `href` attribute that points to where we expect it to point is succficient imo.

```suggestion
```

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +  const { data: CertificateData } = mockCerts;
In general, capitalizing the first letter of things should be reserved for classes/interfaces/types. In this case it's just a variable, so we should use camelCase.

```suggestion
  const { data: certificateData } = mockCerts;
```

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +  it('Checks that the more info button works correctly', () => {
I think something like 

```
renders a button in the <CardActions /> that contains a link to the cert page
```

would be more accurate.

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +  it('Checks that the more info button works correctly', () => {
Whether or not the first letter is capitalized in the `it(''`) is arbitrary so don't worry about that.

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +  it('Checks for expired date and checks the claimed logic', () => {
So what we want to test here is that when the date is expired:

- There is some text that is specific to expired cert cards
- There is an icon that is specific to expired cert cards

I think just a snapshot test would be sufficient to cover that. That would capture both the icon and the text we are looking for.

<hr />

A good test name for that could be 
```
it('renders an expired cert with expired text and warning icon')
```

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +    CertificateData[0].valid_to = 2217110400;
So this line is currently modifying the `CertificateData` object that is shared by all of the other tests. If we were to write another test after this one that relied on the `valid_to` property, it would be dependent upon this test modifying that prop, which is not ideal. 

Something like this will allow us to make a copy of the `CertificateData` that we can modify however we want without affecting other tests.
```suggestion
    const expiredCert = { ...CertificateData, valid_to: 2217110400, assertion_id: 'test' }
```

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +    expect(screen.getByText('Unclaimed'));
Similar to my other comment, I think we can just perform a snapshot test on this rather than needing to test for exact string values.

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +  it('renders', () => {
So for components that can render without any props, I think it's okay to just have a vague `it('renders')` test. e.g. 
```tsx
it('renders', () => {
    const { container } = render(<SpinnerWithLabel>test</SpinnerWithLabel>);
    expect(container).toMatchSnapshot();
  });

  it('renders with a spinner size', () => {
    const { container } = render(
      <SpinnerWithLabel spinnerSize={100}>test</SpinnerWithLabel>,
    );
    expect(container).toMatchSnapshot();
  });
```

In our case though, a certification is required. So I think we should try to be specific about what we are expecting in each test, i.e. `it('renders with...'`

- an active cert
- an expired cert
- a claimed cert
- an unclaimed cert

2020-11-24 18:38 UTC, Patrick-Erichsen commented on src/view/tables/factory/components/CertificatesCell.tsx
> +import { Link } from 'view/components/Links';
```suggestion
import { Link } from 'view/components';
```

2020-11-24 18:41 UTC, Patrick-Erichsen commented on src/view/cards/Certification/__tests__/Certification.spec.tsx
> +    CertificateData[0].valid_to = 2217110400;
However, we only want to test one change at a time, so in this case it should probably just be 

```ts
    const expiredCert = { ...CertificateData, valid_to: 2217110400 }
```

2020-11-24 18:54 UTC, merli027 commented on src/view/cards/Certification/MoreInfoLinkButton.tsx
> +import React from 'react';
Left in. Got an error when removing.

2020-11-24 23:24 UTC, merged